async(page)=>{
 const base='http://localhost:18787',errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.request.post(base+'/api/login',{headers:{Authorization:'Bearer local-browser-test-token-not-for-deployment'},data:{}});
 let previews=0,writes=0;
 page.on('request',r=>{if(r.url().endsWith('/api/preview'))previews++;if(r.method()==='POST'&&r.url().endsWith('/json/state'))writes++;});
 await page.goto(base+'/settings');
 await page.waitForFunction(async()=> (await(await fetch('/api/status')).json()).allowed);
 await page.waitForFunction(()=>document.getElementById('summaryEffect').textContent!=='Checking...');
 await page.waitForTimeout(1500);
 if(previews)throw Error('Preview requested while off by default');
 if(await page.locator('#lightBrightness,#lightEffect,#lightPalette,#lightPrimary,#lightSecondary,#lightThird,#applyLighting,#lightOff').count())throw Error('Duplicate lighting editor remains');
 if(await page.locator('#pixelPreview').isVisible())throw Error('Disabled canvas visible');
 await page.waitForFunction(async()=> (await(await fetch('/api/status')).json()).allowed);
 const applied=await page.request.post(base+'/json/state',{data:{on:true,bri:90,seg:{fx:0,pal:0,col:[[255,0,0],[0,255,0],[0,0,255]]}}});
 if(!applied.ok())throw Error('Fixture lighting update failed: '+await applied.text());
 await page.waitForFunction(()=>document.getElementById('summaryEffect').textContent==='Solid'&&document.getElementById('summaryColors').textContent.includes('Red'));
 await page.route('**/api/preview',route=>route.fulfill({json:{allowed:true,count:2,width:2,height:1,stride:1,pixels:[[0,0,0,255],[1,0,255,0]]}}));
 await page.getByRole('button',{name:'Enable live preview',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('summaryLiveColors').textContent.includes('Blue'));
 if(await page.locator('#previewEnabled').getAttribute('aria-pressed')!=='true'||!await page.locator('#pixelPreview').isVisible())throw Error('Enabled state incorrect');
 await page.waitForTimeout(1200);if(previews<2)throw Error('Preview did not poll');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});
 const hidden=previews;await page.waitForTimeout(1000);
 if(previews!==hidden)throw Error('Hidden page still requests preview');
 await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});
 await page.waitForTimeout(700);
 if(previews===hidden)throw Error('Visible preview did not resume');
 await page.getByRole('button',{name:'Disable live preview',exact:true}).click();
 const stopped=previews;await page.waitForTimeout(1200);
 if(previews!==stopped||await page.locator('#pixelPreview').isVisible())throw Error('Disabled preview still active');
 await page.unroute('**/api/preview');
 let pending;
 await page.route('**/api/preview',route=>{pending=route;});
 await page.locator('#previewEnabled').click();
 await page.waitForTimeout(200);
 await page.locator('#previewEnabled').click();
 if(!pending)throw Error('Missing delayed request');
 await pending.fulfill({json:{allowed:true,count:1,width:1,height:1,stride:1,pixels:[[0,255,0,0]]}}).catch(()=>{});
 const delayedStop=previews;await page.waitForTimeout(1000);
 if(previews!==delayedStop||await page.locator('#pixelPreview').isVisible())throw Error('Late response revived preview');
 await page.unroute('**/api/preview');
 await page.locator('#previewEnabled').click();
 await page.waitForTimeout(600);
 await page.reload();
 await page.waitForFunction(()=>document.getElementById('summaryEffect').textContent==='Solid');
 const reloaded=previews;await page.waitForTimeout(1200);
 if(previews!==reloaded||await page.locator('#previewEnabled').textContent()!=='Enable live preview')throw Error('Reload did not default off');
 if(writes)throw Error('Preview changed lighting state');
 await page.goto(base+'/settings#nightlight');
 if(!await page.locator('#nightlight').evaluate(e=>e.open))throw Error('Timer deep link collapsed');
 await page.locator('#nightMinutes').fill('123');
 await page.waitForTimeout(2500);
 if(await page.locator('#nightMinutes').inputValue()!=='123')throw Error('Status overwrote timer draft');
 if(errors.length)throw Error(errors.join('; '));
 await page.screenshot({path:'build/config-preview-off.png'});
 console.log('Config preview defaults, polling, cancellation, reload, summary and timer draft passed');
}
