// AI: below section was generated by an AI
// Linux adaptation of WLED v16.0.1 interfaces: https://github.com/wled/WLED
#pragma once
extern std::vector<uint32_t> linux_frame;
extern uint8_t linux_brightness;
class Bus {
public:
  unsigned getStart() const {return 0;}
  unsigned getLength() const {return linux_pixels;}
  bool containsPixel(unsigned i) const {return i<linux_pixels;}
  bool isOk() const {return true;}
  bool hasRGB() const {return true;}
  bool hasWhite() const {return linux_rgbw;}
  bool hasCCT() const {return false;}
  uint8_t getAutoWhiteMode() const {return 0;}
  static uint8_t getGlobalAWMode() {return AW_GLOBAL_DISABLED;}
  static int getCCT() {return 127;}
  static void setCCT(int) {}
};
namespace BusManager {
inline Bus bus;
inline unsigned getNumBusses() {return 1;}
inline Bus* getBus(unsigned) {return &bus;}
inline unsigned getTotalLength(bool = false) {return linux_pixels;}
inline bool canAllShow() {return true;}
inline void setBrightness(uint8_t b) {linux_brightness=b;}
inline void setSegmentCCT(int,bool = false) {}
inline void setPixelColor(unsigned i,uint32_t c) {if(i<linux_frame.size()) linux_frame[i]=c;}
inline void show() {}
}

// AI: end
