// AI: below section was generated by an AI
// Linux adaptation of WLED v16.0.1 interfaces: https://github.com/wled/WLED
#pragma once
#include <cstring>
#define PROGMEM
#define PSTR(x) x
#define F(x) x
#define FPSTR(x) x
#define pgm_read_byte(p) (*(const uint8_t*)(p))
#define pgm_read_byte_near(p) pgm_read_byte(p)
#define pgm_read_word(p) (*(const uint16_t*)(p))
#define pgm_read_dword(p) (*(const uint32_t*)(p))
#define pgm_read_float(p) (*(const float*)(p))
#define pgm_read_ptr(p) (*(const void* const*)(p))
#define memcpy_P memcpy
#define strlen_P strlen
#define strcmp_P strcmp
#define strncmp_P strncmp
#define strcpy_P strcpy
#define strncpy_P strncpy
#define strcat_P strcat
#define sprintf_P sprintf
#define snprintf_P snprintf
using PGM_P = const char*;

// AI: end
