// AI: below section was generated by an AI
// Linux adaptation of WLED v16.0.1 interfaces: https://github.com/wled/WLED
#include "wled.h"
uint32_t linux_now=0, linux_seed=0x12345678;
unsigned linux_pixels=30, linux_width=30, linux_height=1;
bool linux_rgbw=false;
std::vector<uint32_t> linux_frame(30);
uint8_t linux_brightness=128;
bool gammaCorrectCol=false, gammaCorrectBri=false, fadeTransition=true, stateChanged=false;
bool realtimeRespectLedMaps=true, useHarmonicRandomPalette=true, useAMPM=false;
byte realtimeMode=0, paletteBlend=0, randomPaletteChangeTime=5, blendingStyle=0, errorFlag=0, bri=128;
bool useMainSegmentOnly=false, arlsDisableGammaCorrection=true;
byte realtimeOverride=0;
byte briOld=128, briT=128, lastRandomIndex=0;
time_t localTime=0;
char serverDescription[33]="WLED for FPP";
uint8_t scaledBri(uint8_t b) {return b;}
const char* monthStr(uint8_t m) {static const char* names[]={"","January","February","March","April","May","June","July","August","September","October","November","December"};return names[m<=12?m:0];}
const char* monthShortStr(uint8_t m) {static const char* names[]={"","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"};return names[m<=12?m:0];}
const char* dayStr(uint8_t d) {static const char* names[]={"","Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};return names[d<=7?d:0];}
const char* dayShortStr(uint8_t d) {static const char* names[]={"","Sun","Mon","Tue","Wed","Thu","Fri","Sat"};return names[d<=7?d:0];}
// Satisfy upstream linkage; the coordinator rejects all sound-reactive effect IDs.
um_data_t* simulateSound(uint8_t) {
  static float volume=0,peak=0,magnitude=0;
  static uint16_t raw=0;
  static uint8_t fft[16]{}, sample=0, maxvol=0, bin=0;
  static void* values[]{&volume,&raw,fft,&sample,&peak,&magnitude,&maxvol,&bin};
  static um_data_t data{values}; return &data;
}
WS2812FX strip;
std::vector<CRGBPalette16> customPalettes;
std::vector<UsermodPalette> usermodPalettes;
extern "C" {
// Initialize one virtual canvas; all C API calls are serialized by the coordinator.
int wled_init(unsigned count,unsigned width,unsigned height,int rgbw,uint32_t seed) {
  if (!count || count>32768 || !width || !height || width*height!=count || (height>1 && (width>255 || height>255))) return -1;
  errorFlag=0;
  linux_pixels=count; linux_width=width; linux_height=height; linux_rgbw=rgbw;
  linux_seed=seed?seed:1; linux_now=0; linux_frame.assign(count,0);
  customPalettes.clear(); customPalettes.reserve(WLED_MAX_CUSTOM_PALETTES);
  strip.finalizeInit(); strip.setTransition(0); strip.setTargetFps(40);
  return errorFlag ? -int(errorFlag) : 0;
}
unsigned wled_modes() {return strip.getModeCount();}
const char* wled_mode(unsigned id) {return id<strip.getModeCount()?strip.getModeData(id):nullptr;}
const char* wled_palettes() {return JSON_palette_names;}
// Convert bounded gradient stops with upstream FastLED interpolation, without
// changing rendering state. Input is index,R,G,B repeated; output is 16 RGBs.
int wled_compile_palette(const uint8_t* stops,unsigned count,uint8_t* out) {
  if (!stops || !out || count<2 || count>18 || stops[0]!=0 || stops[(count-1)*4]!=255) return -1;
  for (unsigned i=1;i<count;++i) if (stops[i*4]<stops[(i-1)*4] || stops[(i-1)*4]==255) return -1;
  CRGBPalette16 palette; palette.loadDynamicGradientPalette(stops);
  for (int i=0;i<16;++i) {out[i*3]=palette[i].r;out[i*3+1]=palette[i].g;out[i*3+2]=palette[i].b;}
  return 0;
}
// Publish precompiled palettes. Initialization reserves all slots, so validated
// updates need no allocation after the coordinator persists the source document.
int wled_custom_palettes(const uint8_t* colors,unsigned count) {
  if (count>WLED_MAX_CUSTOM_PALETTES || (count && !colors)) return -1;
  customPalettes.resize(count);
  for (unsigned p=0;p<count;++p) for (int i=0;i<16;++i) {
    const uint8_t* c=colors+p*48+i*3; customPalettes[p][i]=CRGB(c[0],c[1],c[2]);
  }
  return 0;
}
// Export fixed previews in the upstream /json/palx stop format. Dynamic color
// tokens (IDs 1-5) are supplied by Python; no segment state or RNG is touched.
int wled_palette_preview(unsigned id,uint8_t* out) {
  if (!out || id>=FIXED_PALETTE_COUNT || (id>0 && id<6)) return -1;
  if (id>=DYNAMIC_PALETTE_COUNT+FASTLED_PALETTE_COUNT) {
    const uint8_t* stops=(const uint8_t*)pgm_read_ptr(&gGradientPalettes[id-DYNAMIC_PALETTE_COUNT-FASTLED_PALETTE_COUNT]);
    for (unsigned i=0;i<18;++i) {
      for (unsigned c=0;c<4;++c) out[i*4+c]=pgm_read_byte(stops+i*4+c);
      if (out[i*4]==255) return i+1;
    }
    return -1;
  }
  CRGBPalette16 palette=id==0 ? PartyColors_gc22 : *fastledPalettes[id-DYNAMIC_PALETTE_COUNT];
  for (int i=0;i<16;++i) {out[i*4]=i*16;out[i*4+1]=palette[i].r;out[i*4+2]=palette[i].g;out[i*4+3]=palette[i].b;}
  return 16;
}
// Apply validated segment geometry, mode, colors and base options without hardware I/O.
int wled_segment(unsigned id,unsigned start,unsigned stop,unsigned startY,unsigned stopY,
                 unsigned fx,unsigned speed,unsigned intensity,unsigned palette,
                 uint32_t c0,uint32_t c1,uint32_t c2,unsigned opacity,unsigned options) {
  if(id>=32 || start>=stop || stop>linux_width || startY>=stopY || stopY>linux_height || fx>=strip.getModeCount()) return -1;
  if (palette>=FIXED_PALETTE_COUNT && (palette>WLED_CUSTOM_PALETTE_ID_BASE || WLED_CUSTOM_PALETTE_ID_BASE-palette>=customPalettes.size())) return -1;
  while(strip.getSegmentsNum()<=id) strip.appendSegment(0,linux_width,0,linux_height);
  Segment& seg=strip.getSegment(id);
  seg.setGeometry(start,stop,1,0,0xffff,startY,stopY);
  seg.setMode(fx); seg.speed=speed; seg.intensity=intensity; seg.setPalette(palette);
  seg.setColor(0,c0); seg.setColor(1,c1); seg.setColor(2,c2); seg.setOpacity(opacity);
  seg.setOption(SEG_OPTION_ON,options&1); seg.setOption(SEG_OPTION_REVERSED,options&2);
  seg.setOption(SEG_OPTION_MIRROR,options&4);
  seg.setOption(SEG_OPTION_SELECTED,options&8);
  return 0;
}
void wled_trim(unsigned count) {for(unsigned i=count;i<strip.getSegmentsNum();++i) strip.getSegment(i).stop=0; strip.purgeSegments();}
// Apply upstream custom sliders and matrix flags after setting the segment's mode.
int wled_options(unsigned id,unsigned grouping,unsigned spacing,unsigned offset,unsigned mapping,
                 unsigned c1,unsigned c2,unsigned c3,unsigned flags,const char* name) {
  if(id>=strip.getSegmentsNum() || grouping<1 || grouping>255 || spacing>255 || mapping>7 || c1>255 || c2>255 || c3>31) return -1;
  auto& s=strip.getSegment(id);
  s.setGeometry(s.start,s.stop,grouping,spacing,offset,s.startY,s.stopY,mapping);
  s.custom1=c1;s.custom2=c2;s.custom3=c3;s.check1=flags&1;s.check2=flags&2;s.check3=flags&4;
  s.setOption(SEG_OPTION_REVERSED_Y,flags&8);s.setOption(SEG_OPTION_MIRROR_Y,flags&16);s.setOption(SEG_OPTION_TRANSPOSED,flags&32);
  s.freeze=flags&64;
  if(name) s.setName(name);
  return 0;
}
void wled_brightness(unsigned b,unsigned transition) {strip.setTransition(transition); strip.setBrightness(b);}
void wled_mainsegment(unsigned id) {strip.setMainSegmentId(id);}
// Advance the engine's supplied monotonic clock and export brightness-scaled RGB(W).
int wled_render(uint32_t ms,uint8_t* target,unsigned length) {
  unsigned channels=linux_rgbw?4:3;
  if(length!=linux_pixels*channels) return -1;
  linux_now=ms; localTime=time(nullptr); strip.service();
  for(unsigned i=0;i<linux_pixels;++i) {
    auto c=linux_frame[i];
    target[i*channels]=scale8(R(c),linux_brightness);
    target[i*channels+1]=scale8(G(c),linux_brightness);
    target[i*channels+2]=scale8(B(c),linux_brightness);
    if(channels==4) target[i*channels+3]=scale8(W(c),linux_brightness);
  }
  return errorFlag ? -int(errorFlag) : 0;
}
}

// AI: end
