// AI: below section was generated by an AI
// Linux adaptation of WLED v16.0.1 interfaces: https://github.com/wled/WLED
#pragma once
#include <algorithm>
#include <array>
#include <cmath>
#include <climits>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <cstdio>
#include <ctime>
#include <string>
#include <vector>
#include "pgmspace.h"
using byte = uint8_t;
using boolean = bool;
using String = std::string;
using std::min;
using std::max;
#define IRAM_ATTR
#define WLED_MAX_BUSSES 1
#define LEDC_CHANNEL_MAX 0
#define LEDC_SPEED_MODE_MAX 0
#define MAX_LEDS 32768
#define DEFAULT_LED_COUNT 30
#define DEBUG_PRINT(...)
#define DEBUG_PRINTLN(...)
#define DEBUG_PRINTF(...)
#define DEBUG_PRINTF_P(...)
#define USER_PRINTLN(...)
#define USER_PRINTF(...)
#define yield()
#define bitRead(v,b) (((v) >> (b)) & 1)
#define bitSet(v,b) ((v) |= (1U << (b)))
#define bitClear(v,b) ((v) &= ~(1U << (b)))
#define bitWrite(v,b,x) ((x)?bitSet(v,b):bitClear(v,b))
#define constrain(v,lo,hi) ((v)<(lo)?(lo):((v)>(hi)?(hi):(v)))
#define radians(v) ((v)*0.017453292519943295)
#define DEG_TO_RAD 0.017453292519943295
#define HALF_PI 1.5707963267948966
#define TWO_PI 6.283185307179586
#define M_TWOPI TWO_PI
#define UTF8_LEN(c) ((c)<0x80?1:((c)<0xE0?2:((c)<0xF0?3:4)))
#define PI 3.141592653589793
extern uint32_t linux_now, linux_seed;
extern unsigned linux_pixels, linux_width, linux_height;
extern bool linux_rgbw;
inline uint32_t millis() { return linux_now; }
inline uint32_t micros() { return linux_now*1000; }
inline void delay(unsigned) {}
inline long map(long x,long a,long b,long c,long d) { return (x-a)*(d-c)/(b-a)+c; }
inline uint32_t hw_random() { linux_seed ^= linux_seed << 13; linux_seed ^= linux_seed >> 17; linux_seed ^= linux_seed << 5; return linux_seed; }
inline uint32_t hw_random(uint32_t n) { return uint64_t(hw_random())*n >> 32; }
inline int32_t hw_random(int32_t a,int32_t b) { return a+hw_random(uint32_t(b-a)); }
inline uint16_t hw_random16() { return hw_random(); }
inline uint16_t hw_random16(uint32_t n) { return (hw_random16()*n)>>16; }
inline int16_t hw_random16(int32_t a,int32_t b) { return a+hw_random16(b-a); }
inline uint8_t hw_random8() { return hw_random(); }
inline uint8_t hw_random8(uint32_t n) { return (hw_random8()*n)>>8; }
inline uint8_t hw_random8(uint32_t a,uint32_t b) { return a+hw_random8(b-a); }
#define random hw_random
#define inoise8 perlin8
#define inoise16 perlin16
#define d_malloc malloc
#define d_calloc calloc
#define d_free free
#define p_malloc malloc
#define p_calloc calloc
#define p_free free
#define BFRALLOC_NOBYTEACCESS 1
#define BFRALLOC_PREFER_DRAM 2
#define BFRALLOC_ENFORCE_DRAM 4
#define BFRALLOC_PREFER_PSRAM 8
#define BFRALLOC_ENFORCE_PSRAM 16
#define BFRALLOC_CLEAR 32
inline void* allocate_buffer(size_t n,uint32_t flags) { return flags&BFRALLOC_CLEAR ? calloc(1,n):malloc(n); }
inline size_t getFreeHeapSize() { return 16*1024*1024; }
inline size_t getContiguousFreeHeap() { return getFreeHeapSize(); }
#include "const.h"
#include "colors.h"
#include "fcn_declare.h"
extern bool gammaCorrectCol, gammaCorrectBri, fadeTransition, stateChanged;
extern bool realtimeRespectLedMaps;
extern byte realtimeMode, paletteBlend, randomPaletteChangeTime, blendingStyle, errorFlag, bri;
extern bool useHarmonicRandomPalette;
extern time_t localTime;
inline unsigned hour(time_t t) { tm v{}; localtime_r(&t,&v); return v.tm_hour; }
inline unsigned minute(time_t t) { tm v{}; localtime_r(&t,&v); return v.tm_min; }
inline unsigned second(time_t t) { tm v{}; localtime_r(&t,&v); return v.tm_sec; }
inline unsigned day(time_t t) { tm v{}; localtime_r(&t,&v); return v.tm_mday; }
inline unsigned month(time_t t) { tm v{}; localtime_r(&t,&v); return v.tm_mon+1; }
inline unsigned year(time_t t) { tm v{}; localtime_r(&t,&v); return v.tm_year+1900; }
extern bool useAMPM;
extern char serverDescription[33];
extern bool useMainSegmentOnly, arlsDisableGammaCorrection;
extern byte realtimeOverride;
extern byte briOld, briT, lastRandomIndex;
uint8_t scaledBri(uint8_t b);
int16_t extractModeDefaults(uint8_t mode,const char* key);
uint32_t utf8_decode(const char*,uint8_t*);
size_t utf8_strlen(const char*);
const char* monthShortStr(uint8_t);
const char* monthStr(uint8_t);
const char* dayStr(uint8_t);
const char* dayShortStr(uint8_t);
inline unsigned weekday(time_t t) {tm v{};localtime_r(&t,&v);return v.tm_wday+1;}
struct um_data_t { void** u_data; };
namespace UsermodManager { inline bool getUMData(um_data_t**,int = 0) {return false;} inline void handleOverlayDraw() {} }
um_data_t* simulateSound(uint8_t);
// File-based fonts are excluded; embedded upstream fonts remain available.
class File {
public:
  explicit operator bool() const {return false;}
  size_t size() const {return 0;}
  int read() {return -1;}
  size_t read(uint8_t*,size_t) {return 0;}
  bool seek(size_t,int = 0) {return false;}
  void close() {}
};
inline struct LinuxFS {File open(const char*,const char*) {return {};}} WLED_FS;
#include "bus_manager.h"
#include "FX.h"
extern WS2812FX strip;

// AI: end
