"""Maintainer helper: mirror the tested port into a separate upstream checkout."""
import argparse
from pathlib import Path
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('checkout', type=Path)
args = parser.parse_args()
checkout = args.checkout.resolve()
if not (checkout / 'wled00/FX.cpp').is_file():
    parser.error('target must be an upstream WLED checkout')
branch = subprocess.check_output(['git', '-C', str(checkout), 'branch', '--show-current'], text=True).strip()
if branch != 'linux-fpp-16.0.1':
    parser.error('target must be on the dedicated linux-fpp-16.0.1 branch')
port = checkout / 'ports/fpp-linux'
for name in ['runtime/linux', 'scripts']:
    (port / name).mkdir(parents=True, exist_ok=True)
for path in (ROOT / 'runtime/linux').glob('*'):
    text = path.read_text()
    if not text.startswith('// AI:'):
        text = ('// AI: below section was generated by an AI\n'
                '// Linux adaptation of WLED v16.0.1 interfaces: https://github.com/wled/WLED\n' + text + '\n// AI: end\n')
        path.write_text(text, newline='\n')
    (port / 'runtime/linux' / path.name).write_text(text, newline='\n')
for name in ['scripts/prepare_renderer.py', 'scripts/build-renderer.sh', 'upstream.lock.json']:
    shutil.copyfile(ROOT / name, port / name)
(port / '.gitignore').write_text('build/\n.upstream/\n__pycache__/\n')
(port / 'README.md').write_text('''# WLED Linux rendering port for FPP

Experimental Linux port based on upstream v16.0.1, preserving upstream history
and the original wled00 tree. The explicit preparation step applies virtual-bus,
filesystem and 64-bit pointer adaptations into build/engine. The new platform
wrappers expose a serialized C ABI for RGB/RGBW rendering and segment control.
It includes upstream gradient conversion, custom palette tables and fixed-palette
previews; the plugin coordinator owns palette persistence and validation.

From this directory on Linux, run `bash scripts/build-renderer.sh`.
Output: `build/libwled_linux.so` and `build/ui/`.
Requires Python 3.10+, Git and G++17. No firmware flashing is involved.

The FPP plugin provides state/API compatibility, ownership, supervision, native
device integration and tests: https://github.com/stingerman1/FPP_WLED_10.x
Read its compatibility matrix before use. This is not a complete embedded-WLED
port and has not passed Pi/native-device hardware acceptance.

Linux port code is EUPL 1.2 or later; upstream and bundled dependency notices
remain in the root source tree. All source under ports/fpp-linux was prepared
with AI assistance. The wrappers are mirrored from the plugin repository; update
with its scripts/sync-port.py and pin the resulting commit in that repository.
''')
print(port)
